basic.showNumber(0)
basic.pause(500)
basic.forever(function () {
    basic.showNumber(1)
    basic.pause(100)
    basic.showNumber(2)
    basic.pause(100)
    basic.showNumber(3)
    basic.pause(100)
})
